export const ADD_SLIDE_STYLE = 'ADD_SLIDE_STYLE';
export const SET_GLOBAL_SLIDE_STYLE = 'SET_GLOBAL_SLIDE_STYLE';
export const SYNC_STYLE_STATE = 'SYNC_STYLE_STATE';
export const IMPORT_STYLES = 'IMPORT_STYLES';
export const RESET_STYLES = 'RESET_STYLES';
